apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
  namespace: ollama-chat
spec:
  rules:
    - host: <use.your.dns.name>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-open-webui
                port:
                  number: 8080
